'use strict';

var lodash = require('lodash');

module.exports = function(grunt) {

    // Initial config
    var config = {

        // Read JSON files
        pkg: grunt.file.readJSON('package.json'),

        // Concat files banner
        banner: 'DO NOT EDIT THIS FILE! It is automatically generated by Grunt.',

        // App variables
        app: {
            src: 'app',
            dest: 'dest'
        }
    };

    // Tasks options
    var tasks = {

        concat: {
            collections: {
                options: {
                    banner: '/* ' + config.banner + ' */\n'
                },
                files: {
                    '<%= app.src %>/collections.js': [
                        '<%= app.src %>/collections/*.js'
                    ]
                }
            },
            models: {
                options: {
                    banner: '/* ' + config.banner + ' */\n'
                },
                files: {
                    '<%= app.src %>/models.js': [
                        '<%= app.src %>/models/*.js'
                    ]
                }
            },
            routers: {
                options: {
                    banner: '/* ' + config.banner + ' */\n'
                },
                files: {
                    '<%= app.src %>/routers.js': [
                        '<%= app.src %>/routers/*.js'
                    ]
                }
            },
            templates: {
                options: {
                    banner: '    <!-- ' + config.banner + ' -->\n'
                },
                files: {
                    '<%= app.src %>/templates.html': [
                        '<%= app.src %>/templates/*.html'
                    ]
                }
            },
            views: {
                options: {
                    banner: '/* ' + config.banner + ' */\n'
                },
                files: {
                    '<%= app.src %>/views-list.js': [
                        '<%= app.src %>/views/*-list.js'
                    ],
                    '<%= app.src %>/views.js': [
                        '!<%= app.src %>/views/*-list.js',
                        '<%= app.src %>/views/*.js'
                    ]
                }
            }
        },

        replace: {
            templates: {
                options: {
                    processTemplates: false
                },
                src: ['index.html'],
                overwrite: true,
                replacements: [{
                    from: /<!-- Templates -->[\s\S]*<!-- END Templates -->/g,
                    to: function() {
                        return '<!-- Templates -->\n' + grunt.file.read('app/templates.html') + '\n    <!-- END Templates -->';
                    }
                }]
            }
        }

    };

    // Merge tasks options with config
    lodash.merge(config, tasks);

    require('load-grunt-tasks')(grunt);

    // Default task
    grunt.registerTask('default', 'Default grunt task', function() {
        grunt.task.run(['concat', 'replace']);
    });

    // Tasks aliases
    grunt.registerTask('build', ['default']);

    // Load grunt config
    grunt.initConfig(config);

    // Load all npm tasks at once
    require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

};
