/* DO NOT EDIT THIS FILE! It is automatically generated by Grunt. */
(function() {
    'use strict';

    app.Collection.Note = Backbone.Collection.extend({

        model: app.Model.Note,
        url: '/notes'

    });

})();
