/* DO NOT EDIT THIS FILE! It is automatically generated by Grunt. */
(function() {
    'use strict';

    app.Model.Note = Backbone.Model.extend({

        defaults: {
            title: '',
            content: '',
            createdDate: '',
            isEditing: false,
            isArchived: false
        }

    });

})();

