/* DO NOT EDIT THIS FILE! It is automatically generated by Grunt. */
(function() {
    'use strict';

    app.View.NoteList = Marionette.CompositeView.extend({

        el: '#notes-wrapper',
        template: '#tmpl_note_list',

        childView: app.View.Note,
        childViewContainer: 'div',

        onRender: function() {
            this.$el.find('> div').addClass('masonry-wrapper');

            window.setTimeout(function() {
                $('.masonry-wrapper').masonry({
                    columnWidth: 0,
                    itemSelector: '.note'
                });

                window.masonry = $('.masonry-wrapper').data('masonry');
            }, 2);
        },

        collectionEvents: {
            'sort': 'updateLayout',
            'sync': 'render'
        },

        events: {
            'click .new': 'new'
        },

        updateLayout: function() {
            if (window.masonry) {
                window.masonry.reloadItems();
                window.masonry.layout();
            }
        },

        new: function() {
            this.collection.add({
                title: '',
                content: '',
                createdDate: new Date().getTime(),
                isEditing: false,
                isArchived: false
            });
        }

    });

})();

(function() {
    'use strict';

    app.View.Note = Marionette.ItemView.extend({

        tagName: 'div',
        template: '#tmpl_note',

        onRender: function() {
            this.$el.addClass('note');

            this.$el.find('textarea').each(function() {
                expandTextarea(this);
            }).on('input', function() {
                expandTextarea(this);
            });
        },

        modelEvents: {
            'change': 'render'
        },

        events: {
            'click .save': 'save',
            'click .edit': 'edit',
            'click .delete': 'delete'
        },

        save: function() {
            var title = this.$('.title').val(),
                content = this.$('.content').val();

            if (title === '' || content === '') {
                this.throwError();
                return false;
            }

            this.model.save({
                title: title,
                content: content,
                isEditing: false
            });
        },

        delete: function() {
            this.model.destroy();

            if (window.masonry) {
                window.masonry.reloadItems();
                window.masonry.layout();
            }
        },

        throwError: function() {
            this.$el.css('outline', '1px solid red');
            return false;
        }

    });

})();
